In [50]:
import pandas as pd
import numpy as np

from sklearn import datasets
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2, f_classif, f_regression

In [51]:
wine_dataset = datasets.load_wine()

wine_df = pd.DataFrame(wine_dataset.data, columns=wine_dataset.feature_names)
wine_df.describe()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
count,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000
mean,13.000618,2.336348,2.366517,19.494944,99.741573,2.295112,2.029270,0.361854,1.590899,5.058090,0.957449,2.611685,746.893258
std,0.811827,1.117146,0.274344,3.339564,14.282484,0.625851,0.998859,0.124453,0.572359,2.318286,0.228572,0.709990,314.907474
min,11.030000,0.740000,1.360000,10.600000,70.000000,0.980000,0.340000,0.130000,0.410000,1.280000,0.480000,1.270000,278.000000
25%,12.362500,1.602500,2.210000,17.200000,88.000000,1.742500,1.205000,0.270000,1.250000,3.220000,0.782500,1.937500,500.500000
50%,13.050000,1.865000,2.360000,19.500000,98.000000,2.355000,2.135000,0.340000,1.555000,4.690000,0.965000,2.780000,673.500000
75%,13.677500,3.082500,2.557500,21.500000,107.000000,2.800000,2.875000,0.437500,1.950000,6.200000,1.120000,3.170000,985.000000
max,14.830000,5.800000,3.230000,30.000000,162.000000,3.880000,5.080000,0.660000,3.580000,13.000000,1.710000,4.000000,1680.000000

In [52]:
wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             178 non-null    float64
 4   magnesium                     178 non-null    float64
 5   total_phenols                 178 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    float64
dtypes: float64(13)
memory usage: 18.2 KB

In [53]:
X = wine_dataset.data
y = wine_dataset.target

In [56]:
# Create and fit selector
selector = SelectKBest(chi2)
selector.fit(wine_df, wine_dataset.target)
# Get columns to keep and create new dataframe with those only
cols = selector.get_support(indices=True)
wine_df_new = wine_df.iloc[:,cols]

print('Original number of features:', wine_df.shape)
print(wine_df.columns.values)
print('\nReduced number of features:', wine_df_new.shape)
print(wine_df_new.columns.values)

Original number of features: (178, 13)
['alcohol' 'malic_acid' 'ash' 'alcalinity_of_ash' 'magnesium'
 'total_phenols' 'flavanoids' 'nonflavanoid_phenols' 'proanthocyanins'
 'color_intensity' 'hue' 'od280/od315_of_diluted_wines' 'proline']

Reduced number of features: (178, 10)
['alcohol' 'malic_acid' 'alcalinity_of_ash' 'magnesium' 'total_phenols'
 'flavanoids' 'proanthocyanins' 'color_intensity'
 'od280/od315_of_diluted_wines' 'proline']

In [59]:
f_values, p_values = chi2(wine_df, wine_dataset.target)
reg_summary = pd.DataFrame(wine_df.columns.values, columns=['Features'])
reg_summary ['f-values'] = f_values.round(3)
reg_summary ['p-values'] = p_values.round(3)
reg_summary

                        Features   f-values  p-values
0                        alcohol      5.445     0.066
1                     malic_acid     28.069     0.000
2                            ash      0.743     0.690
3              alcalinity_of_ash     29.384     0.000
4                      magnesium     45.026     0.000
5                  total_phenols     15.623     0.000
6                     flavanoids     63.334     0.000
7           nonflavanoid_phenols      1.815     0.403
8                proanthocyanins      9.368     0.009
9                color_intensity    109.017     0.000
10                           hue      5.183     0.075
11  od280/od315_of_diluted_wines     23.390     0.000
12                       proline  16540.067     0.000